version: '3.9'

services:
    restapi:
        build: .
        container_name: restapi_app
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            DEBUG: "true"


